### ISSUE TITLE
Show "Enter master password (3) attempt(s) remain)" when docker run by ourown certification

### ISSUE THREAD

**Issue by linustseng** [realityforge/docker-busybox-glassfish-domain#2]
After update to the latest version of docker image, we got Enter master password (3) attempt(s) remain) message then stopping start domain. It works when we apply the previous version and we are still studying the cause. 

It might not be the problem of current version due to we use our own certification file. We just feel curious why it won't be happened in 4.1.151.

**Comment by linustseng** [comment]
Finally I resolved the problem. We will generate new master/admin password for each build. So if we would like to use the same config file after upgrade to new build then we should copy the new cacerts.jks and keystore.jks to the original domain1/config 

It might be my fault to not use the docker-busybox-glassfish-domain as the base image but the simple one (docker-busybox-glassfish) but we needed to create domain again or -v to the domain directory at host

**Comment by realityforge** [comment]
Thanks for reporting back
